# -*- coding: utf-8 -*-
"""2318081_MochHuda_EkstraksiFiturPython.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MJf_RXbLb6MCUupG1hhARPXVrUSpwKDI

# **1. Mount Google Drive**
"""

#Untuk mengkoneksikan Google Colab dengan Folder Google Drive
from google.colab import drive
#Untuk memulai proses mounting dari google drive
drive.mount('/content/drive')

"""# **2. Load Data 10 File Citra yang ada pada File Google Drive**


"""

#Melakukan import library os untuk membuat dan menghapus direktori, mengambil isi direktori, dll
import os

#Mendefinisikan variabel untuk menyimpan lokasi folder citra di dalam Google Drive
folder_path = '/content/drive/MyDrive/semester6/komvis/dataset/archive/10dataset'

#Untuk mengubah direktori sesuai dengan nilai variabel folder_path
os.chdir(folder_path)

#Melakukan perulangan dengan kondisi akhir sesuai jumlah isi file di dalam folder
for file_name in os.listdir(folder_path):
    #Mencetak pesan nama file yang ada di dalam folder
    print(f"Nama File: {file_name}")

"""# **3. Melakukan Konversi Citra BGR ke Grayscale**"""

#Melakukan import library opencv yang digunakan untuk melakukan konversi color space
import cv2

#Mendefinisikan variabel untuk menyimpan lokasi folder citra di dalam Google Drive
folder_path = '/content/drive/MyDrive/semester6/komvis/dataset/archive/10dataset'

#Melakukan perulangan dengan kondisi akhir sesuai jumlah isi file di dalam folder
for file_name in os.listdir(folder_path):
    #Menentukan spesifikasi file citra yang akan digunakan, yaitu yang memiliki ekstensi.jpg, .jpeg, dan .png
    if file_name.endswith('.jpg') or file_name.endswith('.jpeg') or file_name.endswith('.png'):
        #Membaca file citra yang ada di dalam folder Google Drive
        image = cv2.imread(os.path.join(folder_path, file_name))
        #Melakukan konversi citra dari BGR menjadi Grayscale
        grayscale_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        #Menyimpan dan mendefinisikan nama file citra hasil konversi ke dalam folder Google Drive
        cv2.imwrite(os.path.join(folder_path, f"grayscale_{file_name}"), grayscale_image)
        #Mencetak pesan berhasil mengkonversi citra
        print(f'File {file_name} berhasil diubah menjadi grayscale.')

"""# **4. Melakukan Ekstraksi Fitur Tekstur pada 10 Citra**"""

#Melakukan import library os untuk membuat dan menghapus direktori, mengambil isi direktori, dll
import os
#Melakukan import library opencv yang digunakan untuk melakukan konversi color space
import cv2
#Melakukan import library NumPy yang digunakan untuk membentuk objek N-dimensional array
import numpy as np
#Melakukan import graycomatrix untuk menghitung matriks co-occurance tingkat keabuan, dan graycoprops untuk menghitung properti tekstur dari GLCM dari library skimage.feature
from skimage.feature import graycomatrix, graycoprops
#Melakukan import library Pandas yang digunakan untuk membaca isi file excel
import pandas as pd

#Mendefinisikan variabel untuk menyimpan lokasi folder citra di dalam Google Drive
folder_path = '/content/drive/MyDrive/semester6/komvis/dataset/archive/10dataset'
#Membuat variabel array kosong yang akan digunakan untuk menampung nilai fitur hasil ekstraksi
nilai_fitur = []

#Melakukan perulangan dengan kondisi akhir sesuai jumlah isi file di dalam folder
for file_name in os.listdir(folder_path):
    #Menentukan spesifikasi file citra yang akan digunakan, yaitu yang memiliki ekstensi.jpg, .jpeg, dan .png
    if file_name.endswith(".jpg") or file_name.endswith('.jpeg') or file_name.endswith(".png"):
        #Membaca file citra yang ada di dalam folder Google Drive
        image = cv2.imread(os.path.join(folder_path, file_name))
        #Melakukan konversi citra dari BGR menjadi Grayscale
        grayscale_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        #Menghitung matriks co-occurance dari citra hasil konversi
        glcm = graycomatrix(grayscale_image, [1], [0, np.pi/4, np.pi/2, 3*np.pi/4], symmetric=True, normed=True)
        #Menghitung rata-rata properti tekstur energi dari GLCM
        energi = graycoprops(glcm, 'energy').mean()
        #Menghitung rata-rata properti tekstur kontras dari GLCM
        kontras = graycoprops(glcm, 'contrast').mean()
        #Menghitung rata-rata properti tekstur korelasi dari GLCM
        korelasi = graycoprops(glcm, 'correlation').mean()
        #Menghitung rata-rata properti tekstur homogenitas dari GLCM
        homogenitas = graycoprops(glcm, 'homogeneity').mean()
        #Menampung nilai fitur ke dalam variabel array nilai_fitur
        nilai_fitur.append([file_name, energi, kontras, korelasi, homogenitas])

        #Mencetak nama file
        print(f"File {file_name}:")
        #Mencetak nilai energi
        print(f"Energi: {energi:.3f}")
        #Mencetak nilai kontras
        print(f"Kontras: {kontras:.3f}")
        #Mencetak nilai korelasi
        print(f"Korelasi: {korelasi:.3f}")
        #Mencetak nilai homogenitas
        print(f"Homogenitas: {homogenitas:.3f}")
    else:
        #Mencetak nama file jika bukan gambar
        print(f"Nama File: {file_name}")

"""# **5. Melakukan Penampungan Nilai-Nilai Fitur ke dalam File .xlsx dan Membuka isi File .xlsx**"""

#Mendefinisikan variabel untuk menyimpan nama kolom pada excel
nama_kolom = ['Nama File', 'Energi', 'Kontras', 'Korelasi', 'Homogenitas']
#Menyimpan nilai-nilai hasil ekstraksi fitur ke dalam dataframe
fitur_dataframe = pd.DataFrame(nilai_fitur, columns=nama_kolom)

#Mendefinisikan variabel untuk menyimpan nama dan ekstensi file
nama_file = '2318081_HasilEkstraksiFitur.xlsx'
#Menyimpan dataframe ke dalam file excel dengan nama sesuai dengan variabel nama_file
fitur_dataframe.to_excel(nama_file, index=False)

#Mencetak pesan bahwa file berhasil disimpan
print(f'File {nama_file} Berhasil Disimpan.')

#Membaca file excel yang sudah dibuat
excel = pd.read_excel('2318081_HasilEkstraksiFitur.xlsx')

#Mencetak isi dari file excel
print(excel)